### ISSUE TITLE
Unable to run example app (google-services.json & GoogleService-Info.plist are missing)

### ISSUE THREAD

**Issue by IjzerenHein** [rmrs/react-native-firebaseui#15]
Hi, I'm working on a new PR for adding placeholder images (the defaultSource prop) to this lib, and I'm running into the issue that I can't run the example app out of the box. This makes development and adding testing of new features rather cumbersome. Would it be possible to have these shipped with this repo, or do you consider this to be a security concern for some reason?
cheers, Hein

**Comment by erezrokah** [comment]
Hey @IjzerenHein you're amazing :)

I don't think it is much of a security concern as the values from these files are embedded in the client app anyway (nothing secret about them and they can be extracted easily, though I think you can enforce their usage only with apps signed by a specific certificate).

Just having any kind of configuration as part of the code seems like bad practice and I think we should encourage people to use their own account (they should do it anyway).

Also, and I'm not sure about this one, if we do have a "generic" versions of these files they are still linked to a specific google account which might lead to abuse of that account (there are limits for the free tier).

Since the setup is a one time thing, I think it is best practice to let people have their own separate environment.

Let me know if this makes any sense to you :)

**Comment by erezrokah** [comment]
More info here:
https://stackoverflow.com/questions/37358340/should-i-add-the-google-services-json-from-firebase-to-my-repository

**Comment by IjzerenHein** [comment]
Hi Erez, thanks for the feedback and the background information. In that case, I will make a setup specifically for this lib.
I completely agree though about the potential abuse that may happen in case of open-sourcing these files. Although it's open source, the cost would end-up at the developer who's trying to do a good thing and give back to the community. At some point it would be nice if giants like Google would recognize this and provide community accounts that serve this purpose. This would also be in their best interest as it becomes easier to develop open-source software for their services.

**Comment by erezrokah** [comment]
I agree it would make sense if google have some testing accounts for the community (and they can throttle it on their side to avoid abuse).

Closing this issue for now
